=== volatilityfoundation/volatility3/volatility3/schemas/schema-6.3.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://volatilityfoundation.org/intermediate-format/schema",
  "title": "Symbol Container",
  "type": "object",
  "definitions": {
    "metadata_producer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string",
          "pattern": "^[0-9]+.[0-9]+.[0-9]+$"
        },
        "datetime": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required":[
        "name",
        "version"
      ]
    },
    "metadata_windows_pe": {
      "type": "object",
      "properties": {
        "major": {
          "type": "integer"
        },
        "minor": {
          "type": "integer"
        },
        "revision": {
          "type": "integer"
        },
        "build": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "major",
        "minor",
        "revision"
      ]
    },
    "metadata_windows_pdb": {
      "type": "object",
      "properties": {
        "GUID": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "database": {
          "type": "string"
        },
        "machine_type": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "GUID",
        "age",
        "database",
        "machine_type"
      ]
    },
    "metadata_windows": {
      "type": "object",
      "properties": {
        "pe": {
          "$ref": "#/definitions/metadata_windows_pe"
        },
        "pdb": {
          "$ref": "#/definitions/metadata_windows_pdb"
        }
      },
      "additionalProperties": false
    },
    "metadata_nix": {
      "type": "object",
      "properties": {
        "symbols": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/metadata_nix_item"
          }
        },
        "types": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/metadata_nix_item"
          }
        }
      },
      "additionalProperties": false
    },
    "metadata_format": {
      "type": "string",
      "pattern": "^6.[0-9]+.[0-9]+$"
    },
    "metadata_nix_item": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(dwarf|symtab|system-map)$"
        },
        "name": {
          "type": "string"
        },
        "hash_type": {
          "type": "string",
          "pattern": "^(sha256)$"
        },
        "hash_value": {
          "type": "string",
          "pattern": "^[a-fA-F0-9]+$"
        }
      },
      "additionalProperties": false
    },
    "element_metadata": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            }
          },
          "required": [
            "format",
            "producer"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "windows": {
              "$ref": "#/definitions/metadata_windows"
            }
          },
          "required": [
            "format",
            "producer",
            "windows"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "linux": {
              "$ref": "#/definitions/metadata_nix"
            }
          },
          "required": [
            "format",
            "producer",
            "linux"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "mac": {
              "$ref": "#/definitions/metadata_nix"
            }
          },
          "required": [
            "format",
            "producer",
            "mac"
          ],
          "additionalProperties": false
        }
      ]
    },
    "element_enum": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "base": {
          "type": "string"
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        }
      },
      "required": [
        "size",
        "base",
        "constants"
      ],
      "additionalProperties": false
    },
    "element_symbol": {
      "properties": {
        "address": {
          "type": "number"
        },
        "linkage_name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "constant_data": {
          "type": "string",
          "media": {
            "binaryEncoding": "base64",
            "readOnly": true
          }
        }
      },
      "required": [
        "address"
      ],
      "additionalProperties": false
    },
    "element_base_type": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "signed": {
          "type": "boolean"
        },
        "kind": {
          "type": "string",
          "pattern": "^(void|int|float|char|bool)$"
        },
        "endian": {
          "type": "string",
          "pattern": "^(little|big)$"
        }
      },
      "required": [
        "size",
        "kind",
        "signed",
        "endian"
      ],
      "additionalProperties": false
    },
    "element_user_type": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|union|class)$"
        },
        "size": {
          "type": "integer"
        },
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": [
        "kind",
        "size",
        "fields"
      ],
      "additionalProperties": false
    },
    "field": {
      "properties": {
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "offset": {
          "type": "integer"
        },
        "anonymous": {
          "type": "boolean"
        }
      },
      "required": [
        "type",
        "offset"
      ],
      "additionalProperties": false
    },
    "type_descriptor": {
      "oneOf": [
        {
          "$ref": "#/definitions/type_pointer"
        },
        {
          "$ref": "#/definitions/type_base"
        },
        {
          "$ref": "#/definitions/type_array"
        },
        {
          "$ref": "#/definitions/type_struct"
        },
        {
          "$ref": "#/definitions/type_enum"
        },
        {
          "$ref": "#/definitions/type_function"
        },
        {
          "$ref": "#/definitions/type_bitfield"
        }
      ]
    },
    "type_pointer": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^pointer$"
        },
        "base": {
          "type": "string"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        }
      },
      "required": [
        "kind",
        "subtype"
      ],
      "additionalProperties": false
    },
    "type_base": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^base$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_array": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^array$"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "kind",
        "subtype",
        "count"
      ],
      "additionalProperties": false
    },
    "type_struct": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|class|union)$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_enum": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^enum$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_function": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^function$"
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "type_bitfield": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^bitfield$"
        },
        "bit_position": {
          "type": "integer"
        },
        "bit_length": {
          "type": "integer"
        },
        "type": {
          "oneOf": [
            {
              "$ref": "#/definitions/type_base"
            },
            {
              "$ref": "#/definitions/type_enum"
            }
          ]
        }
      },
      "required": [
        "kind",
        "bit_position",
        "bit_length",
        "type"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "metadata": {
      "$ref": "#/definitions/element_metadata"
    },
    "base_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_base_type"
      }
    },
    "user_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_user_type"
      }
    },
    "enums": {
      "additionalProperties": {
        "$ref": "#/definitions/element_enum"
      }
    },
    "symbols": {
      "additionalProperties": {
        "$ref": "#/definitions/element_symbol"
      }
    }
  },
  "required": [
    "metadata",
    "base_types",
    "user_types",
    "enums",
    "symbols"
  ],
  "additionalProperties": false
}

=== volatilityfoundation/volatility3/volatility3/framework/symbols/windows/crash64.json
{
  "symbols": {
  },
  "user_types": {
    "_DUMP_HEADER64": {
      "fields": {
        "Signature": {
          "offset": 0,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "ValidDump": {
          "offset": 4,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "MajorVersion": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "MinorVersion": {
          "offset": 12,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "DirectoryTableBase": {
          "offset": 16,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "PfnDataBase": {
          "offset": 24,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "PsLoadedModuleList": {
          "offset": 32,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "PsActiveProcessHead": {
          "offset": 40,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "MachineImageType": {
          "offset": 48,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberProcessors": {
          "offset": 52,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "BugCheckCode": {
          "offset": 56,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "BugCheckCodeParameter": {
          "offset": 64,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned long long"
            }
          }
        },
        "VersionUser": {
          "offset": 96,
          "type": {
            "count": 32,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "KdDebuggerDataBlock": {
          "offset": 128,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "PhysicalMemoryBlockBuffer": {
          "offset": 136,
          "type": {
            "kind": "struct",
            "name": "_PHYSICAL_MEMORY_DESCRIPTOR64"
          }
        },
        "ContextRecord": {
          "offset": 840,
          "type": {
            "count": 3000,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "Exception": {
          "offset": 3840,
          "type": {
            "kind": "struct",
            "name": "_EXCEPTION_RECORD64"
          }
        },
        "DumpType": {
          "offset": 3992,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "RequiredDumpSpace": {
          "offset": 4000,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "SystemTime": {
          "offset": 4008,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "Comment": {
          "offset": 4016,
          "type": {
            "count": 128,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned char"
            }
          }
        },
        "SystemUpTime": {
          "offset": 4144,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "MiniDumpFields": {
          "offset": 4152,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "SecondaryDataState": {
          "offset": 4156,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ProductType": {
          "offset": 4160,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "SuiteMask": {
          "offset": 4164,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "WriterStatus": {
          "offset": 4168,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Unused1": {
          "offset": 4172,
          "type": {
            "kind": "base",
            "name": "unsigned char"
          }
        },
        "KdSecondaryVersion": {
          "offset": 4173,
          "type": {
            "kind": "base",
            "name": "unsigned char"
          }
        },
        "Unused2": {
          "offset": 4174,
          "type": {
            "kind": "base",
            "name": "unsigned char"
          }
        }
      },
      "kind": "struct",
      "size": 8192
    },
    "_EXCEPTION_RECORD64": {
      "fields": {
        "ExceptionCode": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "long"
          }
        },
        "ExceptionFlags": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ExceptionRecord": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "ExceptionAddress": {
          "offset": 16,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "NumberParameters": {
          "offset": 24,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "ExceptionInformation": {
          "offset": 32,
          "type": {
            "count": 15,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "unsigned long long"
            }
          }
        }
      },
      "kind": "struct",
      "size": 152
    },
    "_PHYSICAL_MEMORY_DESCRIPTOR64": {
      "fields": {
        "NumberOfPages": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "NumberOfRuns": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "Run": {
          "offset": 16,
          "type": {
            "count": 1,
            "kind": "array",
            "subtype": {
              "kind": "struct",
              "name": "_PHYSICAL_MEMORY_RUN64"
            }
          }
        }
      },
      "kind": "struct",
      "size": 20
    },
    "_PHYSICAL_MEMORY_RUN64": {
      "fields": {
        "BasePage": {
          "offset": 0,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        },
        "PageCount": {
          "offset": 8,
          "type": {
            "kind": "base",
            "name": "unsigned long long"
          }
        }
      },
      "kind": "struct",
      "size": 16
    }
  },
  "enums": {
  },
  "base_types": {
    "unsigned char": {
      "endian": "little",
      "kind": "char",
      "signed": false,
      "size": 1
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    },
    "char": {
      "endian": "little",
      "kind": "char",
      "signed": true,
      "size": 1
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "long long": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 8
    },
    "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    }
  },
  "metadata": {
    "producer": {
      "version": "0.0.1",
      "name": "ikelos-by-hand",
      "datetime": "2020-09-10T00:20:00"
    },
    "format": "6.2.0"
  }
}

=== volatilityfoundation/volatility3/volatility3/framework/symbols/windows/unloadedmodules-x64.json
{
    "symbols": {},
    "enums": {},
    "base_types": {
        "unsigned long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned long long": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned char": {
            "kind": "char",
            "size": 1,
            "signed": false,
            "endian": "little"
        },
        "pointer": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned int": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "little"
        },
        "long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        }
    },
    "user_types": {
        "_UNLOADED_DRIVER": {
            "fields": {
                "Name": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_UNICODE_STRING"
                    },
                    "offset": 0
                },
                "StartAddress": {
                    "type": {
                        "kind": "base",
                        "name": "unsigned long long"
                    },
                    "offset": 16
                },
                "EndAddress": {
                    "type": {
                        "kind": "base",
                        "name": "unsigned long long"
                    },
                    "offset": 24
                },
                "CurrentTime": {
                    "type": {
                        "kind": "base",
                        "name": "unsigned long long"
                    },
                    "offset": 32
                }
            },
            "kind": "struct",
            "size": 40
        },
        "_UNLOADED_DRIVERS": {
            "fields": {
                "UnloadedDrivers": {
                    "offset": 0,
                    "type": {
                        "count": 1,
                        "kind": "array",
                        "subtype": {
                            "kind": "struct",
                            "name": "_UNLOADED_DRIVER"
                        }
                    }
                }
            },
            "kind": "struct",
            "size": 8
        }
    },
    "metadata": {
        "producer": {
            "version": "0.0.1",
            "name": "Dave Lassalle by hand",
            "datetime": "2024-06-19T17:57:16.394003"
        },
        "format": "4.0.0"
    }
}

=== volatilityfoundation/volatility3/volatility3/framework/symbols/windows/poolheader-x86.json
{
  "metadata": {
    "producer": {
      "version": "0.1.5",
      "name": "mhl-by-hand",
      "datetime": "2018-10-03T16:53:00.478000"
    },
    "format": "4.0.0"
  },
  "user_types": {
    "_POOL_HEADER": {
      "fields": {
        "BlockSize": {
          "offset": 2,
          "type": {
            "bit_length": 9,
            "bit_position": 0,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        },
        "PoolIndex": {
          "offset": 0,
          "type": {
            "bit_length": 7,
            "bit_position": 9,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        },
        "PoolTag": {
          "offset": 4,
          "type": {
            "kind": "base",
            "name": "unsigned long"
          }
        },
        "PoolType": {
          "offset": 2,
          "type": {
            "bit_length": 7,
            "bit_position": 9,
            "kind": "bitfield",
            "type": {
              "kind": "base",
              "name": "unsigned short"
            }
          }
        }
      },
      "kind": "struct",
      "size": 8
    }
  },
  "symbols": {
  },
  "enums": {
  },
  "base_types": {
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    },
    "int": {
      "endian": "little",
      "kind": "int",
      "signed": true,
      "size": 4
    }
  }
}
