=== volatilityfoundation/volatility3/volatility3/schemas/schema-6.3.0.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "http://volatilityfoundation.org/intermediate-format/schema",
  "title": "Symbol Container",
  "type": "object",
  "definitions": {
    "metadata_producer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string",
          "pattern": "^[0-9]+.[0-9]+.[0-9]+$"
        },
        "datetime": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required":[
        "name",
        "version"
      ]
    },
    "metadata_windows_pe": {
      "type": "object",
      "properties": {
        "major": {
          "type": "integer"
        },
        "minor": {
          "type": "integer"
        },
        "revision": {
          "type": "integer"
        },
        "build": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "major",
        "minor",
        "revision"
      ]
    },
    "metadata_windows_pdb": {
      "type": "object",
      "properties": {
        "GUID": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "database": {
          "type": "string"
        },
        "machine_type": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "GUID",
        "age",
        "database",
        "machine_type"
      ]
    },
    "metadata_windows": {
      "type": "object",
      "properties": {
        "pe": {
          "$ref": "#/definitions/metadata_windows_pe"
        },
        "pdb": {
          "$ref": "#/definitions/metadata_windows_pdb"
        }
      },
      "additionalProperties": false
    },
    "metadata_nix": {
      "type": "object",
      "properties": {
        "symbols": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/metadata_nix_item"
          }
        },
        "types": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/metadata_nix_item"
          }
        }
      },
      "additionalProperties": false
    },
    "metadata_format": {
      "type": "string",
      "pattern": "^6.[0-9]+.[0-9]+$"
    },
    "metadata_nix_item": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(dwarf|symtab|system-map)$"
        },
        "name": {
          "type": "string"
        },
        "hash_type": {
          "type": "string",
          "pattern": "^(sha256)$"
        },
        "hash_value": {
          "type": "string",
          "pattern": "^[a-fA-F0-9]+$"
        }
      },
      "additionalProperties": false
    },
    "element_metadata": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            }
          },
          "required": [
            "format",
            "producer"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "windows": {
              "$ref": "#/definitions/metadata_windows"
            }
          },
          "required": [
            "format",
            "producer",
            "windows"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "linux": {
              "$ref": "#/definitions/metadata_nix"
            }
          },
          "required": [
            "format",
            "producer",
            "linux"
          ],
          "additionalProperties": false
        },
        {
          "properties": {
            "format": {
              "$ref": "#/definitions/metadata_format"
            },
            "producer": {
              "$ref": "#/definitions/metadata_producer"
            },
            "mac": {
              "$ref": "#/definitions/metadata_nix"
            }
          },
          "required": [
            "format",
            "producer",
            "mac"
          ],
          "additionalProperties": false
        }
      ]
    },
    "element_enum": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "base": {
          "type": "string"
        },
        "constants": {
          "type": "object",
          "additionalProperties": {
            "type": "integer"
          }
        }
      },
      "required": [
        "size",
        "base",
        "constants"
      ],
      "additionalProperties": false
    },
    "element_symbol": {
      "properties": {
        "address": {
          "type": "number"
        },
        "linkage_name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "constant_data": {
          "type": "string",
          "media": {
            "binaryEncoding": "base64",
            "readOnly": true
          }
        }
      },
      "required": [
        "address"
      ],
      "additionalProperties": false
    },
    "element_base_type": {
      "properties": {
        "size": {
          "type": "integer"
        },
        "signed": {
          "type": "boolean"
        },
        "kind": {
          "type": "string",
          "pattern": "^(void|int|float|char|bool)$"
        },
        "endian": {
          "type": "string",
          "pattern": "^(little|big)$"
        }
      },
      "required": [
        "size",
        "kind",
        "signed",
        "endian"
      ],
      "additionalProperties": false
    },
    "element_user_type": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|union|class)$"
        },
        "size": {
          "type": "integer"
        },
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": [
        "kind",
        "size",
        "fields"
      ],
      "additionalProperties": false
    },
    "field": {
      "properties": {
        "type": {
          "$ref": "#/definitions/type_descriptor"
        },
        "offset": {
          "type": "integer"
        },
        "anonymous": {
          "type": "boolean"
        }
      },
      "required": [
        "type",
        "offset"
      ],
      "additionalProperties": false
    },
    "type_descriptor": {
      "oneOf": [
        {
          "$ref": "#/definitions/type_pointer"
        },
        {
          "$ref": "#/definitions/type_base"
        },
        {
          "$ref": "#/definitions/type_array"
        },
        {
          "$ref": "#/definitions/type_struct"
        },
        {
          "$ref": "#/definitions/type_enum"
        },
        {
          "$ref": "#/definitions/type_function"
        },
        {
          "$ref": "#/definitions/type_bitfield"
        }
      ]
    },
    "type_pointer": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^pointer$"
        },
        "base": {
          "type": "string"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        }
      },
      "required": [
        "kind",
        "subtype"
      ],
      "additionalProperties": false
    },
    "type_base": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^base$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_array": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^array$"
        },
        "subtype": {
          "$ref": "#/definitions/type_descriptor"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "kind",
        "subtype",
        "count"
      ],
      "additionalProperties": false
    },
    "type_struct": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^(struct|class|union)$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_enum": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^enum$"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "name"
      ],
      "additionalProperties": false
    },
    "type_function": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^function$"
        }
      },
      "required": [
        "kind"
      ],
      "additionalProperties": false
    },
    "type_bitfield": {
      "properties": {
        "kind": {
          "type": "string",
          "pattern": "^bitfield$"
        },
        "bit_position": {
          "type": "integer"
        },
        "bit_length": {
          "type": "integer"
        },
        "type": {
          "oneOf": [
            {
              "$ref": "#/definitions/type_base"
            },
            {
              "$ref": "#/definitions/type_enum"
            }
          ]
        }
      },
      "required": [
        "kind",
        "bit_position",
        "bit_length",
        "type"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "metadata": {
      "$ref": "#/definitions/element_metadata"
    },
    "base_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_base_type"
      }
    },
    "user_types": {
      "additionalProperties": {
        "$ref": "#/definitions/element_user_type"
      }
    },
    "enums": {
      "additionalProperties": {
        "$ref": "#/definitions/element_enum"
      }
    },
    "symbols": {
      "additionalProperties": {
        "$ref": "#/definitions/element_symbol"
      }
    }
  },
  "required": [
    "metadata",
    "base_types",
    "user_types",
    "enums",
    "symbols"
  ],
  "additionalProperties": false
}

=== volatilityfoundation/volatility3/volatility3/framework/symbols/windows/callbacks-x64.json
{
    "symbols": {},
    "enums": {},
    "base_types": {
        "unsigned long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned long long": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned char": {
            "kind": "char",
            "size": 1,
            "signed": false,
            "endian": "little"
        },
        "pointer": {
            "kind": "int",
            "size": 8,
            "signed": false,
            "endian": "little"
        },
        "unsigned int": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        },
        "unsigned short": {
            "kind": "int",
            "size": 2,
            "signed": false,
            "endian": "little"
        },
        "long": {
            "kind": "int",
            "size": 4,
            "signed": false,
            "endian": "little"
        }
    },
    "user_types": {
        "_GENERIC_CALLBACK": {
            "fields": {
              "Callback": {
                "type": {
                  "kind": "pointer",
                  "subtype": {
                    "kind": "base",
                    "name": "void"
                  }
                },
                "offset": 8
              }
            },
            "kind": "struct",
            "size": 16
        },
        "_KBUGCHECK_CALLBACK_RECORD": {
            "fields": {
                "Entry": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_LIST_ENTRY"
                    },
                    "offset": 0
                },
                "CallbackRoutine": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 16
                },
                "Component": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned char"
                        }
                    },
                    "offset": 40
                }
            },
            "kind": "struct",
            "size": 64
        },
        "_KBUGCHECK_REASON_CALLBACK_RECORD": {
            "fields": {
                "Entry": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_LIST_ENTRY"
                    },
                    "offset": 0
                },
                "CallbackRoutine": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 16
                },
                "Component": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "unsigned char"
                        }
                    },
                    "offset": 40
                }
            },
            "kind": "struct",
            "size": 64
        },
        "_EX_CALLBACK_ROUTINE_BLOCK": {
            "fields": {
                "Function": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 8
                }
            },
            "kind": "struct",
            "size": 64
        },
        "_CM_CALLBACK_ENTRY": {
            "fields": {
                "Link": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_LIST_ENTRY"
                    },
                    "offset": 0
                },
                "Cookie": {
                    "type": {
                        "kind": "base",
                        "name": "unsigned long long"
                    },
                    "offset": 24
                },
                "Function": {
                    "type": {
                        "kind": "pointer",
                        "subtype": {
                            "kind": "base",
                            "name": "void"
                        }
                    },
                    "offset": 40
                },
                "Altitude": {
                    "type": {
                        "kind": "struct",
                        "name": "nt_symbols!_UNICODE_STRING"
                    },
                    "offset": 48
                }
            },
            "kind": "struct",
            "size": 64
        }
    },
    "metadata": {
        "producer": {
            "version": "0.0.1",
            "name": "mhl by hand",
            "datetime": "2019-08-27T18:17:16.417006"
        },
        "format": "4.0.0"
    }
}

=== volatilityfoundation/volatility3/volatility3/framework/symbols/linux/hash64.json
{
    "symbols": {}, 
    "enums": {}, 
    "base_types": {
        "unsigned char": {
            "kind": "char", 
            "size": 1, 
            "signed": false, 
            "endian": "little"
        }, 
        "pointer": {
            "kind": "int", 
            "size": 8, 
            "signed": false, 
            "endian": "little"
        },
        "int": {
            "kind": "int", 
            "size": 4, 
            "signed": false, 
            "endian": "little"
        }
    }, 
    "user_types": {
        "pathdata": {
            "fields": {
                "path": {
                    "type": {
                        "subtype": {
                            "count": 1024,
                            "subtype": {
                                "kind": "base",
                                "name": "unsigned char"
                            },
                            "kind": "array"
                        },
                        "kind": "pointer"
                    },
                    "offset": 0
                },
                "flags": {
                    "type": {
                        "kind": "base",
                        "name": "int"
                    },
                    "offset": 8
                }
            },
            "kind": "struct",
            "size": 12
        },
        "envdata": {
            "fields": {
                "name": {
                    "type": {
                        "subtype": {
                            "count": 1024,
                            "subtype": {
                                "kind": "base",
                                "name": "unsigned char"
                            },
                            "kind": "array"
                        },
                        "kind": "pointer"
                    },
                    "offset": 0
                },
                "value": {
                    "type": {
                        "subtype": {
                            "count": 1024,
                            "subtype": {
                                "kind": "base",
                                "name": "unsigned char"
                            },
                            "kind": "array"
                        },
                        "kind": "pointer"
                    },
                    "offset": 8
                }
            },
            "kind": "struct",
            "size": 16
        },
        "bucket_contents": {
            "fields": {
                "next": {
                    "type": {
                        "subtype": {
                            "kind": "struct",
                            "name": "bucket_contents"
                        },
                        "kind": "pointer"
                    },
                    "offset": 0
                },
                "key": {
                    "type": {
                        "subtype": {
                            "count": 1024,
                            "subtype": {
                                "kind": "base",
                                "name": "unsigned char"
                            },
                            "kind": "array"
                        },
                        "kind": "pointer"
                    },
                    "offset": 8
                },
                "data": {
                    "type": {
                        "subtype": {
                            "kind": "struct",
                            "name": "pathdata"
                        },
                        "kind": "pointer"
                    },
                    "offset": 16
                },
                "times_found": {
                    "type": {
                        "kind": "base",
                        "name": "int"
                    },
                    "offset": 28
                }
            },
            "kind": "struct",
            "size": 32
        },
        "bash_hash_table": {
            "fields": {
                "bucket_array": {
                    "type": {
                        "subtype": {
                            "kind": "struct",
                            "name": "bucket_contents"
                        },
                        "kind": "pointer"
                    },
                    "offset": 0
                },
                "nbuckets": {
                    "type": {
                        "kind": "base",
                        "name": "int"
                    },
                    "offset": 8
                },
                "nentries": {
                    "type": {
                        "kind": "base",
                        "name": "int"
                    },
                    "offset": 12
                }
            },
            "kind": "struct",
            "size": 16
        }
    },
    "metadata": {
        "producer": {
            "version": "0.0.1", 
            "name": "/mnt/hgfs/volshared/vtypes_to_json.py", 
            "datetime": "2018-12-03T09:55:34.880766"
        }, 
        "format": "4.1.0"
    }
}

=== volatilityfoundation/volatility3/volatility3/symbols/generic/vmcs/westmere-architecture.json
{
  "base_types": {
    "pointer": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    },
    "unsigned char": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 1
    },
    "unsigned long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 4
    },
    "unsigned long long": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 8
    },
    "unsigned short": {
      "endian": "little",
      "kind": "int",
      "signed": false,
      "size": 2
    }
  },
  "enums": {},
  "metadata": {
    "format": "6.1.0",
    "producer": {
      "datetime": "2021-07-31T17:37:28.314801",
      "name": "vmextract-by-hand",
      "version": "0.0.1"
    }
  },
  "symbols": {
    "revision_id": {
      "address": 0,
      "constant_data": "MTU="
    }
  },
  "user_types": {
    "_VMCS": {
      "fields": {
        "ept": {
          "offset": 320,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "executive_vmcs_ptr": {
          "offset": 208,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "guest_cr3": {
          "offset": 736,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "guest_cr4": {
          "offset": 744,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "guest_pdpte": {
          "offset": 928,
          "type": {
            "count": 4,
            "kind": "array",
            "subtype": {
              "kind": "struct",
              "name": "unsigned long long"
            }
          }
        },
        "guest_physical_addr": {
          "offset": 328,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "host_cr3": {
          "offset": 832,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "host_cr4": {
          "offset": 840,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "vmcs_link_ptr": {
          "offset": 248,
          "type": {
            "kind": "struct",
            "name": "unsigned long long"
          }
        },
        "vpid": {
          "offset": 220,
          "type": {
            "kind": "struct",
            "name": "unsigned short"
          }
        }
      },
      "kind": "struct",
      "size": 4096
    }
  }
}
